name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/ngthanhtrung23/verification-helper.git@master

    - name: Install python dependencies
      run: pip3 install "setuptools<81.0.0"

    - name: Cache downloaded test cases
      uses: actions/cache@v4
      with:
        path: .verify-helper/cache
        key: verify-cache-${{ runner.os }}
        restore-keys: |
          verify-cache-${{ runner.os }}

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all --jobs 2
